repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        pass_filenames: false
        files: '^(Cargo\.toml|Cargo\.lock|src/|tests/).*(\.rs)?$'

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --locked --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        files: '^(Cargo\.toml|Cargo\.lock|src/|tests/).*(\.rs)?$'

      - id: cargo-test
        name: cargo test --lib --bins
        entry: cargo test --locked --lib --bins
        language: system
        pass_filenames: false
        files: '^(Cargo\.toml|Cargo\.lock|src/|tests/).*(\.rs)?$'
